### ISSUE TITLE
Uncaught exception with Teku on Windows

### ISSUE THREAD

**Issue by remyroy** [stake-house/eth-wizard#52]
Handle this better with eth-wizard 0.7.3.

```
2022-01-03 13:18:13,924 - ethwizard.platforms.windows10 - CRITICAL - Uncaught exception
Traceback (most recent call last):
  File "C:\Users\Test\AppData\Local\Temp\7zS805612E6\httpx\_transports\default.py", line 62, in map_httpcore_exceptions
    yield
  File "C:\Users\Test\AppData\Local\Temp\7zS805612E6\httpx\_transports\default.py", line 177, in handle_request
    status_code, headers, byte_stream, extensions = self._pool.handle_request(
  File "C:\Users\Test\AppData\Local\Temp\7zS805612E6\httpcore\_sync\connection_pool.py", line 234, in handle_request
    response = connection.handle_request(
  File "C:\Users\Test\AppData\Local\Temp\7zS805612E6\httpcore\_sync\connection.py", line 136, in handle_request
    self.socket = self._open_socket(timeout)
  File "C:\Users\Test\AppData\Local\Temp\7zS805612E6\httpcore\_sync\connection.py", line 163, in _open_socket
    return self._backend.open_tcp_stream(
  File "C:\Users\Test\AppData\Local\Temp\7zS805612E6\httpcore\_backends\sync.py", line 144, in open_tcp_stream
    return SyncSocketStream(sock=sock)
  File "contextlib.py", line 137, in __exit__
  File "C:\Users\Test\AppData\Local\Temp\7zS805612E6\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectError: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Test\AppData\Local\Temp\7zS805612E6\ethwizard\platforms\windows10.py", line 2364, in install_teku
    response = httpx.get(teku_query_url, headers=headers)
  File "C:\Users\Test\AppData\Local\Temp\7zS805612E6\httpx\_api.py", line 189, in get
    return request(
  File "C:\Users\Test\AppData\Local\Temp\7zS805612E6\httpx\_api.py", line 100, in request
    return client.request(
  File "C:\Users\Test\AppData\Local\Temp\7zS805612E6\httpx\_client.py", line 792, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Users\Test\AppData\Local\Temp\7zS805612E6\httpx\_client.py", line 877, in send
    response = self._send_handling_auth(
  File "C:\Users\Test\AppData\Local\Temp\7zS805612E6\httpx\_client.py", line 905, in _send_handling_auth
    response = self._send_handling_redirects(
  File "C:\Users\Test\AppData\Local\Temp\7zS805612E6\httpx\_client.py", line 942, in _send_handling_redirects
    response = self._send_single_request(request)
  File "C:\Users\Test\AppData\Local\Temp\7zS805612E6\httpx\_client.py", line 978, in _send_single_request
    response = transport.handle_request(request)
  File "C:\Users\Test\AppData\Local\Temp\7zS805612E6\httpx\_transports\default.py", line 177, in handle_request
    status_code, headers, byte_stream, extensions = self._pool.handle_request(
  File "contextlib.py", line 137, in __exit__
  File "C:\Users\Test\AppData\Local\Temp\7zS805612E6\httpx\_transports\default.py", line 79, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 197, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Users\Test\AppData\Local\Temp\7zS805612E6\ethwizard\__main__.py", line 4, in <module>
    wizard.run()
  File "C:\Users\Test\AppData\Local\Temp\7zS805612E6\ethwizard\wizard.py", line 88, in run
    sequence.run_from_start()
  File "C:\Users\Test\AppData\Local\Temp\7zS805612E6\ethwizard\platforms\common.py", line 69, in run_from_start
    return self._run_from_index(0, context)
  File "C:\Users\Test\AppData\Local\Temp\7zS805612E6\ethwizard\platforms\common.py", line 119, in _run_from_index
    context = current_step.exc_function(current_step, context, self)
  File "C:\Users\Test\AppData\Local\Temp\7zS805612E6\ethwizard\platforms\windows10.py", line 263, in install_teku_function
    if not install_teku(context[selected_directory], context[selected_network],
  File "C:\Users\Test\AppData\Local\Temp\7zS805612E6\ethwizard\platforms\windows10.py", line 2371, in install_teku
    log_file.seek(-1024, 2)
io.UnsupportedOperation: can't do nonzero end-relative seeks
```

**Comment by remyroy** [comment]
Should be fixed with 8f600f34c1f4e8abe55fcb63867dc2549a98c353
