### ISSUE TITLE
Uncaught exception when trying to update (0.9.2)

### ISSUE THREAD

**Issue by remyroy** [stake-house/eth-wizard#86]
```
2022-11-27 12:24:34,502 - ethwizard.platforms.windows.common - CRITICAL - Uncaught exception
Traceback (most recent call last):
  File "runpy.py", line 197, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Users\user\AppData\Local\Temp\7zS4DA2C4FE\ethwizard\__main__.py", line 4, in <module>
    wizard.run()
  File "C:\Users\user\AppData\Local\Temp\7zS4DA2C4FE\ethwizard\wizard.py", line 68, in run
    enter_maintenance(platform, saved_state['context'])
  File "C:\Users\user\AppData\Local\Temp\7zS4DA2C4FE\ethwizard\platforms\__init__.py", line 174, in enter_maintenance
    return windows10_enter_maintenance(context)
  File "C:\Users\user\AppData\Local\Temp\7zS4DA2C4FE\ethwizard\platforms\windows\maintain.py", line 81, in enter_maintenance
    context = use_default_client(context)
  File "C:\Users\user\AppData\Local\Temp\7zS4DA2C4FE\ethwizard\platforms\windows\maintain.py", line 678, in use_default_client
    if selected_network in context and context[selected_consensus_client] == 'prater':
NameError: name 'selected_network' is not defined 

```

**Comment by remyroy** [comment]
Fixed with 278e7ec100eaaddb7c8ecbb64066306a8b774d85
